# Generated by Django 2.1.7 on 2019-03-15 22:26

from django.db import migrations

from django.db import migrations
from django.conf import settings
import os.path
import csv
from django.utils.text import slugify
# from django.core.files import File

def load_book_data(apps, schema_editor):
    """read a csv file full of free books and insert them into the database"""
    Book = apps.get_model('core', 'Book')
    Topic = apps.get_model('core', 'Book')

    datapath = os.path.join(settings.BASE_DIR, 'initial_data')
    datafile = os.path.join(datapath, 'Book_List.csv')
    with open(datafile) as file:
        reader = csv.DictReader(file)
        for row in reader:

            book_title = row['title']
            topic, _ = Topic.objects.get_or_create(name=row['topic'],slug=slugify(row['topic']))
            
            if Book.objects.filter(title=book_title).count():
                continue
            
            book = Book(
                title=row['title'],
                author=row['author'],
                description=row['description'],
                book_url=row['book_url'],
                slug=slugify(row['title'])[:50],)

            book.save()
            book.topic.set([topic])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190315_1823'),
    ]

    operations = [migrations.RunPython(load_book_data)
    ]
