# Generated by Django 2.1.7 on 2019-03-15 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_load_m2m_topics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='topic',
            new_name='topics',
        ),
    ]
