# Generated by Django 2.1.7 on 2019-03-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190313_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='djangodbmodelsfieldscharfield'),
        ),
    ]
