# Generated by Django 2.1.7 on 2019-03-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_book_book_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name='Date Added'),
        ),
    ]
