# Generated by Django 2.1.7 on 2019-03-17 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190317_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_slug',
            new_name='slug',
        ),
    ]
