# Generated by Django 2.1.7 on 2019-03-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190314_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_topic',
            field=models.ManyToManyField(to='core.Topic'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
