# Generated by Django 2.1.7 on 2019-03-11 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_author_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-date_added']},
        ),
    ]
