# Generated by Django 2.1.7 on 2019-03-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190312_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=2, verbose_name=models.CharField(max_length=200)),
            preserve_default=False,
        ),
    ]
