# Generated by Django 2.1.7 on 2019-03-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190312_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='topics',
        ),
        migrations.AddField(
            model_name='topic',
            name='book_topic',
            field=models.ManyToManyField(related_name='book_topics', to='core.Book'),
        ),
    ]
