# Generated by Django 2.1.7 on 2019-03-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190313_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='book_topic',
        ),
        migrations.AddField(
            model_name='book',
            name='topic',
            field=models.ManyToManyField(related_name='topics', to='core.Topic'),
        ),
    ]
