# Generated by Django 2.1.7 on 2019-03-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_load_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_topic',
            field=models.ManyToManyField(related_name='book_topics', to='core.Topic'),
        ),
    ]
